### ISSUE TITLE
rtkit-daemon: Failed to look up client

### ISSUE THREAD

**Issue by tiiiecherle** [heftig/rtkit#8] opened 2019-03-22 07:53 UTC
Hey,

thanks for maintaining this project. I use archlinux with all packages up-to-date. After upgrading rtkit to 0.12 the systemd service unit itself says it starts but its internal rtkit-daemon command gives the following error. 

`rtkit-daemon[...]: Failed to look up client`

This happens on every boot.

Downgrading to 0.11+10+g493a135-1 solves the problem.

Sorry I can not provide more information. Hope this helps to solve it. Thanks for looking into it in advance.

Kind regards

Tom

**Comment by heftig** [comment] 2019-03-22 11:37
Isn't there any more to this error? It should be followed by a colon and more details.

**Comment by heftig** [comment] 2019-03-22 11:42
Also, are there any failures or warnings preceding it?

**Comment by tiiiecherle** [comment] 2019-03-22 14:41
Showing the log of the systemd unit since its start with this command:
```
unit=rtkit-daemon
ts=$(systemctl show -p ActiveEnterTimestamp $unit)
journalctl -u $unit --since "$(echo $ts | awk '{print $2 $3}')" > /media/sf_files/"$unit"_log.txt
```
gives me
```
Mär 22 15:35:25 archvbox systemd[1]: Starting RealtimeKit Scheduling Policy Service...
Mär 22 15:35:25 archvbox systemd[1]: Started RealtimeKit Scheduling Policy Service.
Mär 22 15:35:25 archvbox rtkit-daemon[1431]: Successfully called chroot.
Mär 22 15:35:25 archvbox rtkit-daemon[1431]: Successfully dropped privileges.
Mär 22 15:35:25 archvbox rtkit-daemon[1431]: Successfully limited resources.
Mär 22 15:35:25 archvbox rtkit-daemon[1431]: Running.
Mär 22 15:35:25 archvbox rtkit-daemon[1431]: Watchdog thread running.
Mär 22 15:35:25 archvbox rtkit-daemon[1431]: Canary thread running.
Mär 22 15:35:25 archvbox rtkit-daemon[1431]: Failed to look up client: No such file or directory
Mär 22 15:35:25 archvbox rtkit-daemon[1431]: Failed to look up client: No such file or directory
Mär 22 15:35:25 archvbox rtkit-daemon[1431]: Failed to look up client: No such file or directory
Mär 22 15:35:25 archvbox rtkit-daemon[1431]: Failed to look up client: No such file or directory
Mär 22 15:35:25 archvbox rtkit-daemon[1431]: Failed to look up client: No such file or directory
Mär 22 15:35:25 archvbox rtkit-daemon[1431]: Failed to look up client: No such file or directory
Mär 22 15:35:25 archvbox rtkit-daemon[1431]: Failed to look up client: No such file or directory
Mär 22 15:35:25 archvbox rtkit-daemon[1431]: Failed to look up client: No such file or directory
Mär 22 15:35:25 archvbox rtkit-daemon[1431]: Failed to look up client: No such file or directory
Mär 22 15:35:25 archvbox rtkit-daemon[1431]: Failed to look up client: No such file or directory
Mär 22 15:35:25 archvbox rtkit-daemon[1431]: Failed to look up client: No such file or directory
Mär 22 15:35:26 archvbox rtkit-daemon[1431]: Supervising 0 threads of 0 processes of 1 users.
Mär 22 15:35:26 archvbox rtkit-daemon[1431]: Failed to look up client: No such file or directory
Mär 22 15:35:26 archvbox rtkit-daemon[1431]: Supervising 0 threads of 0 processes of 1 users.
Mär 22 15:35:26 archvbox rtkit-daemon[1431]: Failed to look up client: No such file or directory
Mär 22 15:35:26 archvbox rtkit-daemon[1431]: Supervising 0 threads of 0 processes of 1 users.
Mär 22 15:35:26 archvbox rtkit-daemon[1431]: Failed to look up client: No such file or directory
Mär 22 15:35:26 archvbox rtkit-daemon[1431]: Supervising 0 threads of 0 processes of 1 users.
Mär 22 15:35:26 archvbox rtkit-daemon[1431]: Failed to look up client: No such file or directory
Mär 22 15:35:26 archvbox rtkit-daemon[1431]: Supervising 0 threads of 0 processes of 1 users.
Mär 22 15:35:26 archvbox rtkit-daemon[1431]: Failed to look up client: No such file or directory
Mär 22 15:35:26 archvbox rtkit-daemon[1431]: Supervising 0 threads of 0 processes of 1 users.
Mär 22 15:35:26 archvbox rtkit-daemon[1431]: Failed to look up client: No such file or directory
Mär 22 15:35:26 archvbox rtkit-daemon[1431]: Supervising 0 threads of 0 processes of 1 users.
Mär 22 15:35:26 archvbox rtkit-daemon[1431]: Failed to look up client: No such file or directory
Mär 22 15:35:26 archvbox rtkit-daemon[1431]: Supervising 0 threads of 0 processes of 1 users.
Mär 22 15:35:26 archvbox rtkit-daemon[1431]: Failed to look up client: No such file or directory
Mär 22 15:35:26 archvbox rtkit-daemon[1431]: Supervising 0 threads of 0 processes of 1 users.
Mär 22 15:35:26 archvbox rtkit-daemon[1431]: Failed to look up client: No such file or directory
Mär 22 15:35:26 archvbox rtkit-daemon[1431]: Supervising 0 threads of 0 processes of 1 users.
Mär 22 15:35:26 archvbox rtkit-daemon[1431]: Failed to look up client: No such file or directory
```

**Comment by heftig** [comment] 2019-03-22 14:49
Does it work again if you add `CAP_SYS_PTRACE` to the `CapabilityBoundingSet` in `/usr/lib/systemd/system/rtkit-daemon.service`, then reboot?

**Comment by tiiiecherle** [comment] 2019-03-22 15:01
Unfortunately still not working with the suggested entry.

**Comment by heftig** [comment] 2019-09-08 11:37
Are you using `hidepid`?

**Comment by tiiiecherle** [comment] 2019-09-09 11:08
> Are you using `hidepid`?

Yes. The respective entry in /etc/fstab is 
`proc /proc proc rw,nosuid,nodev,noexec,hidepid=2,gid=proc 0 0`

And /etc/systemd/system/systemd-logind.service.d/hidepid.conf contains:
```
[Service]
SupplementaryGroups=proc
```

**Comment by heftig** [comment] 2019-09-09 11:17
Okay, I'm moving this conversation to #9, then.

Duplicate of #9.

**Closed as completed by heftig** 2019-09-09 11:17 UTC
